// Code generated by protoc-gen-go. DO NOT EDIT.
// source: porpackage.proto

package por

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PorPackage struct {
	VoteForHeight        uint32    `protobuf:"varint,1,opt,name=VoteForHeight" json:"VoteForHeight,omitempty"`
	Owner                []byte    `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	BlockHash            []byte    `protobuf:"bytes,3,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	TxHash               []byte    `protobuf:"bytes,4,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	SigHash              []byte    `protobuf:"bytes,5,opt,name=SigHash,proto3" json:"SigHash,omitempty"`
	SigChain             *SigChain `protobuf:"bytes,6,opt,name=SigChain" json:"SigChain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PorPackage) Reset()         { *m = PorPackage{} }
func (m *PorPackage) String() string { return proto.CompactTextString(m) }
func (*PorPackage) ProtoMessage()    {}
func (*PorPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_porpackage_3fde0915c79f1a4e, []int{0}
}
func (m *PorPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PorPackage.Unmarshal(m, b)
}
func (m *PorPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PorPackage.Marshal(b, m, deterministic)
}
func (dst *PorPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PorPackage.Merge(dst, src)
}
func (m *PorPackage) XXX_Size() int {
	return xxx_messageInfo_PorPackage.Size(m)
}
func (m *PorPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_PorPackage.DiscardUnknown(m)
}

var xxx_messageInfo_PorPackage proto.InternalMessageInfo

func (m *PorPackage) GetVoteForHeight() uint32 {
	if m != nil {
		return m.VoteForHeight
	}
	return 0
}

func (m *PorPackage) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *PorPackage) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *PorPackage) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *PorPackage) GetSigHash() []byte {
	if m != nil {
		return m.SigHash
	}
	return nil
}

func (m *PorPackage) GetSigChain() *SigChain {
	if m != nil {
		return m.SigChain
	}
	return nil
}

func init() {
	proto.RegisterType((*PorPackage)(nil), "por.PorPackage")
}

func init() { proto.RegisterFile("porpackage.proto", fileDescriptor_porpackage_3fde0915c79f1a4e) }

var fileDescriptor_porpackage_3fde0915c79f1a4e = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0xc8, 0x2f, 0x2a,
	0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0xc8,
	0x2f, 0x92, 0xe2, 0x2b, 0xce, 0x4c, 0x4f, 0xce, 0x48, 0xcc, 0xcc, 0x83, 0x08, 0x2a, 0x1d, 0x66,
	0xe4, 0xe2, 0x0a, 0xc8, 0x2f, 0x0a, 0x80, 0xa8, 0x14, 0x52, 0xe1, 0xe2, 0x0d, 0xcb, 0x2f, 0x49,
	0x75, 0xcb, 0x2f, 0xf2, 0x48, 0xcd, 0x4c, 0xcf, 0x28, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d,
	0x42, 0x15, 0x14, 0x12, 0xe1, 0x62, 0xf5, 0x2f, 0xcf, 0x4b, 0x2d, 0x92, 0x60, 0x52, 0x60, 0xd4,
	0xe0, 0x09, 0x82, 0x70, 0x84, 0x64, 0xb8, 0x38, 0x9d, 0x72, 0xf2, 0x93, 0xb3, 0x3d, 0x12, 0x8b,
	0x33, 0x24, 0x98, 0xc1, 0x32, 0x08, 0x01, 0x21, 0x31, 0x2e, 0xb6, 0x90, 0x0a, 0xb0, 0x14, 0x0b,
	0x58, 0x0a, 0xca, 0x13, 0x92, 0xe0, 0x62, 0x0f, 0xce, 0x4c, 0x07, 0x4b, 0xb0, 0x82, 0x25, 0x60,
	0x5c, 0x21, 0x4d, 0x2e, 0x8e, 0xe0, 0xcc, 0x74, 0x67, 0x90, 0x63, 0x25, 0xd8, 0x14, 0x18, 0x35,
	0xb8, 0x8d, 0x78, 0xf5, 0x0a, 0xf2, 0x8b, 0xf4, 0x60, 0x82, 0x41, 0x70, 0xe9, 0x24, 0x36, 0xb0,
	0x67, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x57, 0xcd, 0x43, 0xf5, 0x00, 0x00, 0x00,
}
