// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: nodemessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_PLACEHOLDER_DO_NOT_USE       MessageType = 0 // Placeholder, do not use or change
	MessageType_VOTE                                      MessageType = 1
	MessageType_I_HAVE_BLOCK_PROPOSAL                     MessageType = 2
	MessageType_REQUEST_BLOCK_PROPOSAL                    MessageType = 3
	MessageType_REQUEST_BLOCK_PROPOSAL_REPLY              MessageType = 4
	MessageType_GET_CONSENSUS_STATE                       MessageType = 5
	MessageType_GET_CONSENSUS_STATE_REPLY                 MessageType = 6
	MessageType_GET_BLOCK_HEADERS                         MessageType = 7
	MessageType_GET_BLOCK_HEADERS_REPLY                   MessageType = 8
	MessageType_GET_BLOCKS                                MessageType = 9
	MessageType_GET_BLOCKS_REPLY                          MessageType = 10
	MessageType_RELAY                                     MessageType = 11
	MessageType_TRANSACTIONS                              MessageType = 12
	MessageType_BACKTRACK_SIGNATURE_CHAIN                 MessageType = 13
	MessageType_REQUEST_PROPOSAL_TRANSACTIONS             MessageType = 14
	MessageType_REQUEST_PROPOSAL_TRANSACTIONS_REPLY       MessageType = 15
	MessageType_I_HAVE_SIGNATURE_CHAIN_TRANSACTION        MessageType = 16
	MessageType_REQUEST_SIGNATURE_CHAIN_TRANSACTION       MessageType = 17
	MessageType_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY MessageType = 18
	MessageType_PIN_SIGNATURE_CHAIN                       MessageType = 19
	MessageType_SIGNATURE_CHAIN_OBJECTION                 MessageType = 20
	MessageType_GET_STATES                                MessageType = 21
	MessageType_GET_STATES_REPLY                          MessageType = 22
	// sync txn pool
	MessageType_REQ_TXN_POOL_HASH MessageType = 23 // request txn pool hash
	MessageType_RPL_TXN_POOL_HASH MessageType = 24 // reply txn pool hash
	MessageType_REQ_SYNC_TXN_POOL MessageType = 25 // request to sync txn pool
	MessageType_RPL_SYNC_TXN_POOL MessageType = 26 // reply to sync txn pool
	// sync random address transaction
	MessageType_REQ_ADDR_NONCE    MessageType = 27 // reques for random address and nonce
	MessageType_RPL_ADDR_NONCE    MessageType = 28 // reply random address and nonce in txn pool
	MessageType_REQ_SYNC_ADDR_TXN MessageType = 29 // request for syncing this address transactions
	MessageType_RPL_SYNC_ADDR_TXN MessageType = 30 // reply this address' transactions
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_PLACEHOLDER_DO_NOT_USE",
		1:  "VOTE",
		2:  "I_HAVE_BLOCK_PROPOSAL",
		3:  "REQUEST_BLOCK_PROPOSAL",
		4:  "REQUEST_BLOCK_PROPOSAL_REPLY",
		5:  "GET_CONSENSUS_STATE",
		6:  "GET_CONSENSUS_STATE_REPLY",
		7:  "GET_BLOCK_HEADERS",
		8:  "GET_BLOCK_HEADERS_REPLY",
		9:  "GET_BLOCKS",
		10: "GET_BLOCKS_REPLY",
		11: "RELAY",
		12: "TRANSACTIONS",
		13: "BACKTRACK_SIGNATURE_CHAIN",
		14: "REQUEST_PROPOSAL_TRANSACTIONS",
		15: "REQUEST_PROPOSAL_TRANSACTIONS_REPLY",
		16: "I_HAVE_SIGNATURE_CHAIN_TRANSACTION",
		17: "REQUEST_SIGNATURE_CHAIN_TRANSACTION",
		18: "REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY",
		19: "PIN_SIGNATURE_CHAIN",
		20: "SIGNATURE_CHAIN_OBJECTION",
		21: "GET_STATES",
		22: "GET_STATES_REPLY",
		23: "REQ_TXN_POOL_HASH",
		24: "RPL_TXN_POOL_HASH",
		25: "REQ_SYNC_TXN_POOL",
		26: "RPL_SYNC_TXN_POOL",
		27: "REQ_ADDR_NONCE",
		28: "RPL_ADDR_NONCE",
		29: "REQ_SYNC_ADDR_TXN",
		30: "RPL_SYNC_ADDR_TXN",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_PLACEHOLDER_DO_NOT_USE":       0,
		"VOTE":                                      1,
		"I_HAVE_BLOCK_PROPOSAL":                     2,
		"REQUEST_BLOCK_PROPOSAL":                    3,
		"REQUEST_BLOCK_PROPOSAL_REPLY":              4,
		"GET_CONSENSUS_STATE":                       5,
		"GET_CONSENSUS_STATE_REPLY":                 6,
		"GET_BLOCK_HEADERS":                         7,
		"GET_BLOCK_HEADERS_REPLY":                   8,
		"GET_BLOCKS":                                9,
		"GET_BLOCKS_REPLY":                          10,
		"RELAY":                                     11,
		"TRANSACTIONS":                              12,
		"BACKTRACK_SIGNATURE_CHAIN":                 13,
		"REQUEST_PROPOSAL_TRANSACTIONS":             14,
		"REQUEST_PROPOSAL_TRANSACTIONS_REPLY":       15,
		"I_HAVE_SIGNATURE_CHAIN_TRANSACTION":        16,
		"REQUEST_SIGNATURE_CHAIN_TRANSACTION":       17,
		"REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY": 18,
		"PIN_SIGNATURE_CHAIN":                       19,
		"SIGNATURE_CHAIN_OBJECTION":                 20,
		"GET_STATES":                                21,
		"GET_STATES_REPLY":                          22,
		"REQ_TXN_POOL_HASH":                         23,
		"RPL_TXN_POOL_HASH":                         24,
		"REQ_SYNC_TXN_POOL":                         25,
		"RPL_SYNC_TXN_POOL":                         26,
		"REQ_ADDR_NONCE":                            27,
		"RPL_ADDR_NONCE":                            28,
		"REQ_SYNC_ADDR_TXN":                         29,
		"RPL_SYNC_ADDR_TXN":                         30,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{0}
}

// Message type that can be signed message
// Name doesn't matter, but value needs to match the value in MessageType
type AllowedSignedMessageType int32

const (
	AllowedSignedMessageType_ALLOW_SIGNED_PLACEHOLDER_DO_NOT_USE AllowedSignedMessageType = 0 // Placeholder, do not use or change
)

// Enum value maps for AllowedSignedMessageType.
var (
	AllowedSignedMessageType_name = map[int32]string{
		0: "ALLOW_SIGNED_PLACEHOLDER_DO_NOT_USE",
	}
	AllowedSignedMessageType_value = map[string]int32{
		"ALLOW_SIGNED_PLACEHOLDER_DO_NOT_USE": 0,
	}
)

func (x AllowedSignedMessageType) Enum() *AllowedSignedMessageType {
	p := new(AllowedSignedMessageType)
	*p = x
	return p
}

func (x AllowedSignedMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedSignedMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[1].Descriptor()
}

func (AllowedSignedMessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[1]
}

func (x AllowedSignedMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllowedSignedMessageType.Descriptor instead.
func (AllowedSignedMessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{1}
}

// Message type that can be unsigned message
// Name doesn't matter, but value needs to match the value in MessageType
type AllowedUnsignedMessageType int32

const (
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_PLACEHOLDER_DO_NOT_USE                    AllowedUnsignedMessageType = 0 // Placeholder, do not use or change
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_VOTE                                      AllowedUnsignedMessageType = 1
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_I_HAVE_BLOCK_PROPOSAL                     AllowedUnsignedMessageType = 2
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQUEST_BLOCK_PROPOSAL                    AllowedUnsignedMessageType = 3
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQUEST_BLOCK_REPLY                       AllowedUnsignedMessageType = 4
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_CONSENSUS_STATE                       AllowedUnsignedMessageType = 5
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_CONSENSUS_STATE_REPLY                 AllowedUnsignedMessageType = 6
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_BLOCK_HEADERS                         AllowedUnsignedMessageType = 7
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_BLOCK_HEADERS_REPLY                   AllowedUnsignedMessageType = 8
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_BLOCKS                                AllowedUnsignedMessageType = 9
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_BLOCKS_REPLY                          AllowedUnsignedMessageType = 10
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_RELAY                                     AllowedUnsignedMessageType = 11
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_TRANSACTIONS                              AllowedUnsignedMessageType = 12
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_BACKTRACK_SIGNATURE_CHAIN                 AllowedUnsignedMessageType = 13
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS             AllowedUnsignedMessageType = 14
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS_REPLY       AllowedUnsignedMessageType = 15
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_I_HAVE_SIGNATURE_CHAIN_TRANSACTION        AllowedUnsignedMessageType = 16
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION       AllowedUnsignedMessageType = 17
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY AllowedUnsignedMessageType = 18
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_PIN_SIGNATURE_CHAIN                       AllowedUnsignedMessageType = 19
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_SIGNATURE_CHAIN_OBJECTION                 AllowedUnsignedMessageType = 20
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_STATES                                AllowedUnsignedMessageType = 21
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_GET_STATES_REPLY                          AllowedUnsignedMessageType = 22
	// sync txn pool
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQ_TXN_POOL_HASH AllowedUnsignedMessageType = 23 // request txn pool hash
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_RPL_TXN_POOL_HASH AllowedUnsignedMessageType = 24 // reply txn pool hash
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQ_SYNC_TXN_POOL AllowedUnsignedMessageType = 25 // request to sync txn pool
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_RPL_SYNC_TXN_POOL AllowedUnsignedMessageType = 26 // reply to sync txn pool
	// sync random address transaction
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQ_ADDR_NONCE    AllowedUnsignedMessageType = 27 // reques for random address and nonce
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_RPL_ADDR_NONCE    AllowedUnsignedMessageType = 28 // reply random address and nonce in txn pool
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_REQ_SYNC_ADDR_TXN AllowedUnsignedMessageType = 29 // request for syncing this address transactions
	AllowedUnsignedMessageType_ALLOW_UNSIGNED_RPL_SYNC_ADDR_TXN AllowedUnsignedMessageType = 30 // reply this address' transactions
)

// Enum value maps for AllowedUnsignedMessageType.
var (
	AllowedUnsignedMessageType_name = map[int32]string{
		0:  "ALLOW_UNSIGNED_PLACEHOLDER_DO_NOT_USE",
		1:  "ALLOW_UNSIGNED_VOTE",
		2:  "ALLOW_UNSIGNED_I_HAVE_BLOCK_PROPOSAL",
		3:  "ALLOW_UNSIGNED_REQUEST_BLOCK_PROPOSAL",
		4:  "ALLOW_UNSIGNED_REQUEST_BLOCK_REPLY",
		5:  "ALLOW_UNSIGNED_GET_CONSENSUS_STATE",
		6:  "ALLOW_UNSIGNED_GET_CONSENSUS_STATE_REPLY",
		7:  "ALLOW_UNSIGNED_GET_BLOCK_HEADERS",
		8:  "ALLOW_UNSIGNED_GET_BLOCK_HEADERS_REPLY",
		9:  "ALLOW_UNSIGNED_GET_BLOCKS",
		10: "ALLOW_UNSIGNED_GET_BLOCKS_REPLY",
		11: "ALLOW_UNSIGNED_RELAY",
		12: "ALLOW_UNSIGNED_TRANSACTIONS",
		13: "ALLOW_UNSIGNED_BACKTRACK_SIGNATURE_CHAIN",
		14: "ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS",
		15: "ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS_REPLY",
		16: "ALLOW_UNSIGNED_I_HAVE_SIGNATURE_CHAIN_TRANSACTION",
		17: "ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION",
		18: "ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY",
		19: "ALLOW_UNSIGNED_PIN_SIGNATURE_CHAIN",
		20: "ALLOW_UNSIGNED_SIGNATURE_CHAIN_OBJECTION",
		21: "ALLOW_UNSIGNED_GET_STATES",
		22: "ALLOW_UNSIGNED_GET_STATES_REPLY",
		23: "ALLOW_UNSIGNED_REQ_TXN_POOL_HASH",
		24: "ALLOW_UNSIGNED_RPL_TXN_POOL_HASH",
		25: "ALLOW_UNSIGNED_REQ_SYNC_TXN_POOL",
		26: "ALLOW_UNSIGNED_RPL_SYNC_TXN_POOL",
		27: "ALLOW_UNSIGNED_REQ_ADDR_NONCE",
		28: "ALLOW_UNSIGNED_RPL_ADDR_NONCE",
		29: "ALLOW_UNSIGNED_REQ_SYNC_ADDR_TXN",
		30: "ALLOW_UNSIGNED_RPL_SYNC_ADDR_TXN",
	}
	AllowedUnsignedMessageType_value = map[string]int32{
		"ALLOW_UNSIGNED_PLACEHOLDER_DO_NOT_USE":                    0,
		"ALLOW_UNSIGNED_VOTE":                                      1,
		"ALLOW_UNSIGNED_I_HAVE_BLOCK_PROPOSAL":                     2,
		"ALLOW_UNSIGNED_REQUEST_BLOCK_PROPOSAL":                    3,
		"ALLOW_UNSIGNED_REQUEST_BLOCK_REPLY":                       4,
		"ALLOW_UNSIGNED_GET_CONSENSUS_STATE":                       5,
		"ALLOW_UNSIGNED_GET_CONSENSUS_STATE_REPLY":                 6,
		"ALLOW_UNSIGNED_GET_BLOCK_HEADERS":                         7,
		"ALLOW_UNSIGNED_GET_BLOCK_HEADERS_REPLY":                   8,
		"ALLOW_UNSIGNED_GET_BLOCKS":                                9,
		"ALLOW_UNSIGNED_GET_BLOCKS_REPLY":                          10,
		"ALLOW_UNSIGNED_RELAY":                                     11,
		"ALLOW_UNSIGNED_TRANSACTIONS":                              12,
		"ALLOW_UNSIGNED_BACKTRACK_SIGNATURE_CHAIN":                 13,
		"ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS":             14,
		"ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS_REPLY":       15,
		"ALLOW_UNSIGNED_I_HAVE_SIGNATURE_CHAIN_TRANSACTION":        16,
		"ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION":       17,
		"ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY": 18,
		"ALLOW_UNSIGNED_PIN_SIGNATURE_CHAIN":                       19,
		"ALLOW_UNSIGNED_SIGNATURE_CHAIN_OBJECTION":                 20,
		"ALLOW_UNSIGNED_GET_STATES":                                21,
		"ALLOW_UNSIGNED_GET_STATES_REPLY":                          22,
		"ALLOW_UNSIGNED_REQ_TXN_POOL_HASH":                         23,
		"ALLOW_UNSIGNED_RPL_TXN_POOL_HASH":                         24,
		"ALLOW_UNSIGNED_REQ_SYNC_TXN_POOL":                         25,
		"ALLOW_UNSIGNED_RPL_SYNC_TXN_POOL":                         26,
		"ALLOW_UNSIGNED_REQ_ADDR_NONCE":                            27,
		"ALLOW_UNSIGNED_RPL_ADDR_NONCE":                            28,
		"ALLOW_UNSIGNED_REQ_SYNC_ADDR_TXN":                         29,
		"ALLOW_UNSIGNED_RPL_SYNC_ADDR_TXN":                         30,
	}
)

func (x AllowedUnsignedMessageType) Enum() *AllowedUnsignedMessageType {
	p := new(AllowedUnsignedMessageType)
	*p = x
	return p
}

func (x AllowedUnsignedMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedUnsignedMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[2].Descriptor()
}

func (AllowedUnsignedMessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[2]
}

func (x AllowedUnsignedMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllowedUnsignedMessageType.Descriptor instead.
func (AllowedUnsignedMessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{2}
}

// Message type that can be sent as direct message
// Name doesn't matter, but value needs to match the value in MessageType
type AllowedDirectMessageType int32

const (
	AllowedDirectMessageType_ALLOW_DIRECT_PLACEHOLDER_DO_NOT_USE                    AllowedDirectMessageType = 0 // Placeholder, do not use or change
	AllowedDirectMessageType_ALLOW_DIRECT_VOTE                                      AllowedDirectMessageType = 1
	AllowedDirectMessageType_ALLOW_DIRECT_I_HAVE_BLOCK_PROPOSAL                     AllowedDirectMessageType = 2
	AllowedDirectMessageType_ALLOW_DIRECT_REQUEST_BLOCK_PROPOSAL                    AllowedDirectMessageType = 3
	AllowedDirectMessageType_ALLOW_DIRECT_REQUEST_BLOCK_REPLY                       AllowedDirectMessageType = 4
	AllowedDirectMessageType_ALLOW_DIRECT_GET_CONSENSUS_STATE                       AllowedDirectMessageType = 5
	AllowedDirectMessageType_ALLOW_DIRECT_GET_CONSENSUS_STATE_REPLY                 AllowedDirectMessageType = 6
	AllowedDirectMessageType_ALLOW_DIRECT_GET_BLOCK_HEADERS                         AllowedDirectMessageType = 7
	AllowedDirectMessageType_ALLOW_DIRECT_GET_BLOCK_HEADERS_REPLY                   AllowedDirectMessageType = 8
	AllowedDirectMessageType_ALLOW_DIRECT_GET_BLOCKS                                AllowedDirectMessageType = 9
	AllowedDirectMessageType_ALLOW_DIRECT_GET_BLOCKS_REPLY                          AllowedDirectMessageType = 10
	AllowedDirectMessageType_ALLOW_DIRECT_BACKTRACK_SIGNATURE_CHAIN                 AllowedDirectMessageType = 13
	AllowedDirectMessageType_ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS             AllowedDirectMessageType = 14
	AllowedDirectMessageType_ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS_REPLY       AllowedDirectMessageType = 15
	AllowedDirectMessageType_ALLOW_DIRECT_I_HAVE_SIGNATURE_CHAIN_TRANSACTION        AllowedDirectMessageType = 16
	AllowedDirectMessageType_ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION       AllowedDirectMessageType = 17
	AllowedDirectMessageType_ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY AllowedDirectMessageType = 18
	AllowedDirectMessageType_ALLOW_DIRECT_PIN_SIGNATURE_CHAIN                       AllowedDirectMessageType = 19
	AllowedDirectMessageType_ALLOW_DIRECT_SIGNATURE_CHAIN_OBJECTION                 AllowedDirectMessageType = 20
	AllowedDirectMessageType_ALLOW_DIRECT_GET_STATES                                AllowedDirectMessageType = 21
	AllowedDirectMessageType_ALLOW_DIRECT_GET_STATES_REPLY                          AllowedDirectMessageType = 22
	// sync txn pool
	AllowedDirectMessageType_ALLOW_DIRECT_REQ_TXN_POOL_HASH AllowedDirectMessageType = 23 // request txn pool hash
	AllowedDirectMessageType_ALLOW_DIRECT_RPL_TXN_POOL_HASH AllowedDirectMessageType = 24 // reply txn pool hash
	AllowedDirectMessageType_ALLOW_DIRECT_REQ_SYNC_TXN_POOL AllowedDirectMessageType = 25 // request to sync txn pool
	AllowedDirectMessageType_ALLOW_DIRECT_RPL_SYNC_TXN_POOL AllowedDirectMessageType = 26 // reply to sync txn pool
	// sync random address transaction
	AllowedDirectMessageType_ALLOW_DIRECT_REQ_ADDR_NONCE    AllowedDirectMessageType = 27 // reques for random address and nonce
	AllowedDirectMessageType_ALLOW_DIRECT_RPL_ADDR_NONCE    AllowedDirectMessageType = 28 // reply random address and nonce in txn pool
	AllowedDirectMessageType_ALLOW_DIRECT_REQ_SYNC_ADDR_TXN AllowedDirectMessageType = 29 // request for syncing this address transactions
	AllowedDirectMessageType_ALLOW_DIRECT_RPL_SYNC_ADDR_TXN AllowedDirectMessageType = 30 // reply this address' transactions
)

// Enum value maps for AllowedDirectMessageType.
var (
	AllowedDirectMessageType_name = map[int32]string{
		0:  "ALLOW_DIRECT_PLACEHOLDER_DO_NOT_USE",
		1:  "ALLOW_DIRECT_VOTE",
		2:  "ALLOW_DIRECT_I_HAVE_BLOCK_PROPOSAL",
		3:  "ALLOW_DIRECT_REQUEST_BLOCK_PROPOSAL",
		4:  "ALLOW_DIRECT_REQUEST_BLOCK_REPLY",
		5:  "ALLOW_DIRECT_GET_CONSENSUS_STATE",
		6:  "ALLOW_DIRECT_GET_CONSENSUS_STATE_REPLY",
		7:  "ALLOW_DIRECT_GET_BLOCK_HEADERS",
		8:  "ALLOW_DIRECT_GET_BLOCK_HEADERS_REPLY",
		9:  "ALLOW_DIRECT_GET_BLOCKS",
		10: "ALLOW_DIRECT_GET_BLOCKS_REPLY",
		13: "ALLOW_DIRECT_BACKTRACK_SIGNATURE_CHAIN",
		14: "ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS",
		15: "ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS_REPLY",
		16: "ALLOW_DIRECT_I_HAVE_SIGNATURE_CHAIN_TRANSACTION",
		17: "ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION",
		18: "ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY",
		19: "ALLOW_DIRECT_PIN_SIGNATURE_CHAIN",
		20: "ALLOW_DIRECT_SIGNATURE_CHAIN_OBJECTION",
		21: "ALLOW_DIRECT_GET_STATES",
		22: "ALLOW_DIRECT_GET_STATES_REPLY",
		23: "ALLOW_DIRECT_REQ_TXN_POOL_HASH",
		24: "ALLOW_DIRECT_RPL_TXN_POOL_HASH",
		25: "ALLOW_DIRECT_REQ_SYNC_TXN_POOL",
		26: "ALLOW_DIRECT_RPL_SYNC_TXN_POOL",
		27: "ALLOW_DIRECT_REQ_ADDR_NONCE",
		28: "ALLOW_DIRECT_RPL_ADDR_NONCE",
		29: "ALLOW_DIRECT_REQ_SYNC_ADDR_TXN",
		30: "ALLOW_DIRECT_RPL_SYNC_ADDR_TXN",
	}
	AllowedDirectMessageType_value = map[string]int32{
		"ALLOW_DIRECT_PLACEHOLDER_DO_NOT_USE":                    0,
		"ALLOW_DIRECT_VOTE":                                      1,
		"ALLOW_DIRECT_I_HAVE_BLOCK_PROPOSAL":                     2,
		"ALLOW_DIRECT_REQUEST_BLOCK_PROPOSAL":                    3,
		"ALLOW_DIRECT_REQUEST_BLOCK_REPLY":                       4,
		"ALLOW_DIRECT_GET_CONSENSUS_STATE":                       5,
		"ALLOW_DIRECT_GET_CONSENSUS_STATE_REPLY":                 6,
		"ALLOW_DIRECT_GET_BLOCK_HEADERS":                         7,
		"ALLOW_DIRECT_GET_BLOCK_HEADERS_REPLY":                   8,
		"ALLOW_DIRECT_GET_BLOCKS":                                9,
		"ALLOW_DIRECT_GET_BLOCKS_REPLY":                          10,
		"ALLOW_DIRECT_BACKTRACK_SIGNATURE_CHAIN":                 13,
		"ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS":             14,
		"ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS_REPLY":       15,
		"ALLOW_DIRECT_I_HAVE_SIGNATURE_CHAIN_TRANSACTION":        16,
		"ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION":       17,
		"ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY": 18,
		"ALLOW_DIRECT_PIN_SIGNATURE_CHAIN":                       19,
		"ALLOW_DIRECT_SIGNATURE_CHAIN_OBJECTION":                 20,
		"ALLOW_DIRECT_GET_STATES":                                21,
		"ALLOW_DIRECT_GET_STATES_REPLY":                          22,
		"ALLOW_DIRECT_REQ_TXN_POOL_HASH":                         23,
		"ALLOW_DIRECT_RPL_TXN_POOL_HASH":                         24,
		"ALLOW_DIRECT_REQ_SYNC_TXN_POOL":                         25,
		"ALLOW_DIRECT_RPL_SYNC_TXN_POOL":                         26,
		"ALLOW_DIRECT_REQ_ADDR_NONCE":                            27,
		"ALLOW_DIRECT_RPL_ADDR_NONCE":                            28,
		"ALLOW_DIRECT_REQ_SYNC_ADDR_TXN":                         29,
		"ALLOW_DIRECT_RPL_SYNC_ADDR_TXN":                         30,
	}
)

func (x AllowedDirectMessageType) Enum() *AllowedDirectMessageType {
	p := new(AllowedDirectMessageType)
	*p = x
	return p
}

func (x AllowedDirectMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedDirectMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[3].Descriptor()
}

func (AllowedDirectMessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[3]
}

func (x AllowedDirectMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllowedDirectMessageType.Descriptor instead.
func (AllowedDirectMessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{3}
}

// Message type that can be sent as relay message
// Name doesn't matter, but value needs to match the value in MessageType
type AllowedRelayMessageType int32

const (
	AllowedRelayMessageType_ALLOW_RELAY_PLACEHOLDER_DO_NOT_USE AllowedRelayMessageType = 0 // Placeholder, do not use or change
	AllowedRelayMessageType_ALLOW_RELAY_RELAY                  AllowedRelayMessageType = 11
)

// Enum value maps for AllowedRelayMessageType.
var (
	AllowedRelayMessageType_name = map[int32]string{
		0:  "ALLOW_RELAY_PLACEHOLDER_DO_NOT_USE",
		11: "ALLOW_RELAY_RELAY",
	}
	AllowedRelayMessageType_value = map[string]int32{
		"ALLOW_RELAY_PLACEHOLDER_DO_NOT_USE": 0,
		"ALLOW_RELAY_RELAY":                  11,
	}
)

func (x AllowedRelayMessageType) Enum() *AllowedRelayMessageType {
	p := new(AllowedRelayMessageType)
	*p = x
	return p
}

func (x AllowedRelayMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedRelayMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[4].Descriptor()
}

func (AllowedRelayMessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[4]
}

func (x AllowedRelayMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllowedRelayMessageType.Descriptor instead.
func (AllowedRelayMessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{4}
}

// Message type that can be sent as broadcast_push message
// Name doesn't matter, but value needs to match the value in MessageType
type AllowedBroadcastPushMessageType int32

const (
	AllowedBroadcastPushMessageType_ALLOW_BROADCAST_PUSH_PLACEHOLDER_DO_NOT_USE AllowedBroadcastPushMessageType = 0 // Placeholder, do not use or change
	AllowedBroadcastPushMessageType_ALLOW_BROADCAST_PUSH_TRANSACTIONS           AllowedBroadcastPushMessageType = 12
)

// Enum value maps for AllowedBroadcastPushMessageType.
var (
	AllowedBroadcastPushMessageType_name = map[int32]string{
		0:  "ALLOW_BROADCAST_PUSH_PLACEHOLDER_DO_NOT_USE",
		12: "ALLOW_BROADCAST_PUSH_TRANSACTIONS",
	}
	AllowedBroadcastPushMessageType_value = map[string]int32{
		"ALLOW_BROADCAST_PUSH_PLACEHOLDER_DO_NOT_USE": 0,
		"ALLOW_BROADCAST_PUSH_TRANSACTIONS":           12,
	}
)

func (x AllowedBroadcastPushMessageType) Enum() *AllowedBroadcastPushMessageType {
	p := new(AllowedBroadcastPushMessageType)
	*p = x
	return p
}

func (x AllowedBroadcastPushMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedBroadcastPushMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[5].Descriptor()
}

func (AllowedBroadcastPushMessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[5]
}

func (x AllowedBroadcastPushMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllowedBroadcastPushMessageType.Descriptor instead.
func (AllowedBroadcastPushMessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{5}
}

// Message type that can be sent as broadcast_pull message
// Name doesn't matter, but value needs to match the value in MessageType
type AllowedBroadcastPullMessageType int32

const (
	AllowedBroadcastPullMessageType_ALLOW_BROADCAST_PULL_PLACEHOLDER_DO_NOT_USE AllowedBroadcastPullMessageType = 0 // Placeholder, do not use or change
)

// Enum value maps for AllowedBroadcastPullMessageType.
var (
	AllowedBroadcastPullMessageType_name = map[int32]string{
		0: "ALLOW_BROADCAST_PULL_PLACEHOLDER_DO_NOT_USE",
	}
	AllowedBroadcastPullMessageType_value = map[string]int32{
		"ALLOW_BROADCAST_PULL_PLACEHOLDER_DO_NOT_USE": 0,
	}
)

func (x AllowedBroadcastPullMessageType) Enum() *AllowedBroadcastPullMessageType {
	p := new(AllowedBroadcastPullMessageType)
	*p = x
	return p
}

func (x AllowedBroadcastPullMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedBroadcastPullMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[6].Descriptor()
}

func (AllowedBroadcastPullMessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[6]
}

func (x AllowedBroadcastPullMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllowedBroadcastPullMessageType.Descriptor instead.
func (AllowedBroadcastPullMessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{6}
}

// Message type that can be sent as broadcast_tree message
// Name doesn't matter, but value needs to match the value in MessageType
type AllowedBroadcastTreeMessageType int32

const (
	AllowedBroadcastTreeMessageType_ALLOW_BROADCAST_TREE_PLACEHOLDER_DO_NOT_USE AllowedBroadcastTreeMessageType = 0 // Placeholder, do not use or change
	AllowedBroadcastTreeMessageType_ALLOW_BROADCAST_TREE_TRANSACTIONS           AllowedBroadcastTreeMessageType = 12
)

// Enum value maps for AllowedBroadcastTreeMessageType.
var (
	AllowedBroadcastTreeMessageType_name = map[int32]string{
		0:  "ALLOW_BROADCAST_TREE_PLACEHOLDER_DO_NOT_USE",
		12: "ALLOW_BROADCAST_TREE_TRANSACTIONS",
	}
	AllowedBroadcastTreeMessageType_value = map[string]int32{
		"ALLOW_BROADCAST_TREE_PLACEHOLDER_DO_NOT_USE": 0,
		"ALLOW_BROADCAST_TREE_TRANSACTIONS":           12,
	}
)

func (x AllowedBroadcastTreeMessageType) Enum() *AllowedBroadcastTreeMessageType {
	p := new(AllowedBroadcastTreeMessageType)
	*p = x
	return p
}

func (x AllowedBroadcastTreeMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllowedBroadcastTreeMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[7].Descriptor()
}

func (AllowedBroadcastTreeMessageType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[7]
}

func (x AllowedBroadcastTreeMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllowedBroadcastTreeMessageType.Descriptor instead.
func (AllowedBroadcastTreeMessageType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{7}
}

type RequestTransactionType int32

const (
	RequestTransactionType_REQUEST_FULL_TRANSACTION       RequestTransactionType = 0
	RequestTransactionType_REQUEST_TRANSACTION_HASH       RequestTransactionType = 1
	RequestTransactionType_REQUEST_TRANSACTION_SHORT_HASH RequestTransactionType = 2
)

// Enum value maps for RequestTransactionType.
var (
	RequestTransactionType_name = map[int32]string{
		0: "REQUEST_FULL_TRANSACTION",
		1: "REQUEST_TRANSACTION_HASH",
		2: "REQUEST_TRANSACTION_SHORT_HASH",
	}
	RequestTransactionType_value = map[string]int32{
		"REQUEST_FULL_TRANSACTION":       0,
		"REQUEST_TRANSACTION_HASH":       1,
		"REQUEST_TRANSACTION_SHORT_HASH": 2,
	}
)

func (x RequestTransactionType) Enum() *RequestTransactionType {
	p := new(RequestTransactionType)
	*p = x
	return p
}

func (x RequestTransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestTransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_nodemessage_proto_enumTypes[8].Descriptor()
}

func (RequestTransactionType) Type() protoreflect.EnumType {
	return &file_nodemessage_proto_enumTypes[8]
}

func (x RequestTransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestTransactionType.Descriptor instead.
func (RequestTransactionType) EnumDescriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{8}
}

type UnsignedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=pb.MessageType" json:"message_type,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsignedMessage) Reset() {
	*x = UnsignedMessage{}
	mi := &file_nodemessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsignedMessage) ProtoMessage() {}

func (x *UnsignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsignedMessage.ProtoReflect.Descriptor instead.
func (*UnsignedMessage) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{0}
}

func (x *UnsignedMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_PLACEHOLDER_DO_NOT_USE
}

func (x *UnsignedMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SignedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedMessage) Reset() {
	*x = SignedMessage{}
	mi := &file_nodemessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedMessage) ProtoMessage() {}

func (x *SignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedMessage.ProtoReflect.Descriptor instead.
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{1}
}

func (x *SignedMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_nodemessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{2}
}

func (x *Vote) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Vote) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type IHaveBlockProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IHaveBlockProposal) Reset() {
	*x = IHaveBlockProposal{}
	mi := &file_nodemessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IHaveBlockProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IHaveBlockProposal) ProtoMessage() {}

func (x *IHaveBlockProposal) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IHaveBlockProposal.ProtoReflect.Descriptor instead.
func (*IHaveBlockProposal) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{3}
}

func (x *IHaveBlockProposal) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *IHaveBlockProposal) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type RequestBlockProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Type          RequestTransactionType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.RequestTransactionType" json:"type,omitempty"`
	ShortHashSalt []byte                 `protobuf:"bytes,3,opt,name=short_hash_salt,json=shortHashSalt,proto3" json:"short_hash_salt,omitempty"`
	ShortHashSize uint32                 `protobuf:"varint,4,opt,name=short_hash_size,json=shortHashSize,proto3" json:"short_hash_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBlockProposal) Reset() {
	*x = RequestBlockProposal{}
	mi := &file_nodemessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBlockProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBlockProposal) ProtoMessage() {}

func (x *RequestBlockProposal) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBlockProposal.ProtoReflect.Descriptor instead.
func (*RequestBlockProposal) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{4}
}

func (x *RequestBlockProposal) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *RequestBlockProposal) GetType() RequestTransactionType {
	if x != nil {
		return x.Type
	}
	return RequestTransactionType_REQUEST_FULL_TRANSACTION
}

func (x *RequestBlockProposal) GetShortHashSalt() []byte {
	if x != nil {
		return x.ShortHashSalt
	}
	return nil
}

func (x *RequestBlockProposal) GetShortHashSize() uint32 {
	if x != nil {
		return x.ShortHashSize
	}
	return 0
}

type RequestBlockProposalReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Block            *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	TransactionsHash [][]byte               `protobuf:"bytes,2,rep,name=transactions_hash,json=transactionsHash,proto3" json:"transactions_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestBlockProposalReply) Reset() {
	*x = RequestBlockProposalReply{}
	mi := &file_nodemessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBlockProposalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBlockProposalReply) ProtoMessage() {}

func (x *RequestBlockProposalReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBlockProposalReply.ProtoReflect.Descriptor instead.
func (*RequestBlockProposalReply) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{5}
}

func (x *RequestBlockProposalReply) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *RequestBlockProposalReply) GetTransactionsHash() [][]byte {
	if x != nil {
		return x.TransactionsHash
	}
	return nil
}

type RequestProposalTransactions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockHash        []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Type             RequestTransactionType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.RequestTransactionType" json:"type,omitempty"`
	ShortHashSalt    []byte                 `protobuf:"bytes,3,opt,name=short_hash_salt,json=shortHashSalt,proto3" json:"short_hash_salt,omitempty"`
	ShortHashSize    uint32                 `protobuf:"varint,4,opt,name=short_hash_size,json=shortHashSize,proto3" json:"short_hash_size,omitempty"`
	TransactionsHash [][]byte               `protobuf:"bytes,5,rep,name=transactions_hash,json=transactionsHash,proto3" json:"transactions_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestProposalTransactions) Reset() {
	*x = RequestProposalTransactions{}
	mi := &file_nodemessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProposalTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProposalTransactions) ProtoMessage() {}

func (x *RequestProposalTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProposalTransactions.ProtoReflect.Descriptor instead.
func (*RequestProposalTransactions) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{6}
}

func (x *RequestProposalTransactions) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *RequestProposalTransactions) GetType() RequestTransactionType {
	if x != nil {
		return x.Type
	}
	return RequestTransactionType_REQUEST_FULL_TRANSACTION
}

func (x *RequestProposalTransactions) GetShortHashSalt() []byte {
	if x != nil {
		return x.ShortHashSalt
	}
	return nil
}

func (x *RequestProposalTransactions) GetShortHashSize() uint32 {
	if x != nil {
		return x.ShortHashSize
	}
	return 0
}

func (x *RequestProposalTransactions) GetTransactionsHash() [][]byte {
	if x != nil {
		return x.TransactionsHash
	}
	return nil
}

type RequestProposalTransactionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProposalTransactionsReply) Reset() {
	*x = RequestProposalTransactionsReply{}
	mi := &file_nodemessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProposalTransactionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProposalTransactionsReply) ProtoMessage() {}

func (x *RequestProposalTransactionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProposalTransactionsReply.ProtoReflect.Descriptor instead.
func (*RequestProposalTransactionsReply) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{7}
}

func (x *RequestProposalTransactionsReply) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetConsensusState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsensusState) Reset() {
	*x = GetConsensusState{}
	mi := &file_nodemessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsensusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsensusState) ProtoMessage() {}

func (x *GetConsensusState) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsensusState.ProtoReflect.Descriptor instead.
func (*GetConsensusState) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{8}
}

type GetConsensusStateReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LedgerBlockHash     []byte                 `protobuf:"bytes,2,opt,name=ledger_block_hash,json=ledgerBlockHash,proto3" json:"ledger_block_hash,omitempty"`
	LedgerHeight        uint32                 `protobuf:"varint,1,opt,name=ledger_height,json=ledgerHeight,proto3" json:"ledger_height,omitempty"`
	ConsensusHeight     uint32                 `protobuf:"varint,3,opt,name=consensus_height,json=consensusHeight,proto3" json:"consensus_height,omitempty"`
	MinVerifiableHeight uint32                 `protobuf:"varint,5,opt,name=min_verifiable_height,json=minVerifiableHeight,proto3" json:"min_verifiable_height,omitempty"`
	SyncState           SyncState              `protobuf:"varint,4,opt,name=sync_state,json=syncState,proto3,enum=pb.SyncState" json:"sync_state,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetConsensusStateReply) Reset() {
	*x = GetConsensusStateReply{}
	mi := &file_nodemessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsensusStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsensusStateReply) ProtoMessage() {}

func (x *GetConsensusStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsensusStateReply.ProtoReflect.Descriptor instead.
func (*GetConsensusStateReply) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{9}
}

func (x *GetConsensusStateReply) GetLedgerBlockHash() []byte {
	if x != nil {
		return x.LedgerBlockHash
	}
	return nil
}

func (x *GetConsensusStateReply) GetLedgerHeight() uint32 {
	if x != nil {
		return x.LedgerHeight
	}
	return 0
}

func (x *GetConsensusStateReply) GetConsensusHeight() uint32 {
	if x != nil {
		return x.ConsensusHeight
	}
	return 0
}

func (x *GetConsensusStateReply) GetMinVerifiableHeight() uint32 {
	if x != nil {
		return x.MinVerifiableHeight
	}
	return 0
}

func (x *GetConsensusStateReply) GetSyncState() SyncState {
	if x != nil {
		return x.SyncState
	}
	return SyncState_WAIT_FOR_SYNCING
}

type GetBlockHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   uint32                 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight     uint32                 `protobuf:"varint,2,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeaders) Reset() {
	*x = GetBlockHeaders{}
	mi := &file_nodemessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeaders) ProtoMessage() {}

func (x *GetBlockHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeaders.ProtoReflect.Descriptor instead.
func (*GetBlockHeaders) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlockHeaders) GetStartHeight() uint32 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *GetBlockHeaders) GetEndHeight() uint32 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

type GetBlockHeadersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeaders  []*Header              `protobuf:"bytes,1,rep,name=block_headers,json=blockHeaders,proto3" json:"block_headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeadersReply) Reset() {
	*x = GetBlockHeadersReply{}
	mi := &file_nodemessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeadersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeadersReply) ProtoMessage() {}

func (x *GetBlockHeadersReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeadersReply.ProtoReflect.Descriptor instead.
func (*GetBlockHeadersReply) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlockHeadersReply) GetBlockHeaders() []*Header {
	if x != nil {
		return x.BlockHeaders
	}
	return nil
}

type GetBlocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   uint32                 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight     uint32                 `protobuf:"varint,2,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocks) Reset() {
	*x = GetBlocks{}
	mi := &file_nodemessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocks) ProtoMessage() {}

func (x *GetBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocks.ProtoReflect.Descriptor instead.
func (*GetBlocks) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlocks) GetStartHeight() uint32 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *GetBlocks) GetEndHeight() uint32 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

type GetBlocksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksReply) Reset() {
	*x = GetBlocksReply{}
	mi := &file_nodemessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksReply) ProtoMessage() {}

func (x *GetBlocksReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksReply.ProtoReflect.Descriptor instead.
func (*GetBlocksReply) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{13}
}

func (x *GetBlocksReply) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_nodemessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{14}
}

func (x *StateRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type StateNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []byte                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateNode) Reset() {
	*x = StateNode{}
	mi := &file_nodemessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateNode) ProtoMessage() {}

func (x *StateNode) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateNode.ProtoReflect.Descriptor instead.
func (*StateNode) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{15}
}

func (x *StateNode) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

type GetStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqs          []*StateRequest        `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStates) Reset() {
	*x = GetStates{}
	mi := &file_nodemessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStates) ProtoMessage() {}

func (x *GetStates) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStates.ProtoReflect.Descriptor instead.
func (*GetStates) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{16}
}

func (x *GetStates) GetReqs() []*StateRequest {
	if x != nil {
		return x.Reqs
	}
	return nil
}

type GetStatesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*StateNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatesReply) Reset() {
	*x = GetStatesReply{}
	mi := &file_nodemessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesReply) ProtoMessage() {}

func (x *GetStatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesReply.ProtoReflect.Descriptor instead.
func (*GetStatesReply) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatesReply) GetNodes() []*StateNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Relay struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SrcIdentifier     string                 `protobuf:"bytes,1,opt,name=src_identifier,json=srcIdentifier,proto3" json:"src_identifier,omitempty"`
	SrcPubkey         []byte                 `protobuf:"bytes,6,opt,name=src_pubkey,json=srcPubkey,proto3" json:"src_pubkey,omitempty"`
	DestId            []byte                 `protobuf:"bytes,2,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	Payload           []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxHoldingSeconds uint32                 `protobuf:"varint,5,opt,name=max_holding_seconds,json=maxHoldingSeconds,proto3" json:"max_holding_seconds,omitempty"`
	// It is important to use block hash instead of block height here to allow
	// node in syncing state to be able to sign the sigchain elem.
	BlockHash     []byte `protobuf:"bytes,7,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	LastHash      []byte `protobuf:"bytes,8,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	SigChainLen   uint32 `protobuf:"varint,9,opt,name=sig_chain_len,json=sigChainLen,proto3" json:"sig_chain_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relay) Reset() {
	*x = Relay{}
	mi := &file_nodemessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relay) ProtoMessage() {}

func (x *Relay) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relay.ProtoReflect.Descriptor instead.
func (*Relay) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{18}
}

func (x *Relay) GetSrcIdentifier() string {
	if x != nil {
		return x.SrcIdentifier
	}
	return ""
}

func (x *Relay) GetSrcPubkey() []byte {
	if x != nil {
		return x.SrcPubkey
	}
	return nil
}

func (x *Relay) GetDestId() []byte {
	if x != nil {
		return x.DestId
	}
	return nil
}

func (x *Relay) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Relay) GetMaxHoldingSeconds() uint32 {
	if x != nil {
		return x.MaxHoldingSeconds
	}
	return 0
}

func (x *Relay) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Relay) GetLastHash() []byte {
	if x != nil {
		return x.LastHash
	}
	return nil
}

func (x *Relay) GetSigChainLen() uint32 {
	if x != nil {
		return x.SigChainLen
	}
	return 0
}

type Transactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transactions) Reset() {
	*x = Transactions{}
	mi := &file_nodemessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactions) ProtoMessage() {}

func (x *Transactions) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactions.ProtoReflect.Descriptor instead.
func (*Transactions) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{19}
}

func (x *Transactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type BacktrackSignatureChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SigChainElems []*SigChainElem        `protobuf:"bytes,1,rep,name=sig_chain_elems,json=sigChainElems,proto3" json:"sig_chain_elems,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktrackSignatureChain) Reset() {
	*x = BacktrackSignatureChain{}
	mi := &file_nodemessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktrackSignatureChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktrackSignatureChain) ProtoMessage() {}

func (x *BacktrackSignatureChain) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktrackSignatureChain.ProtoReflect.Descriptor instead.
func (*BacktrackSignatureChain) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{20}
}

func (x *BacktrackSignatureChain) GetSigChainElems() []*SigChainElem {
	if x != nil {
		return x.SigChainElems
	}
	return nil
}

func (x *BacktrackSignatureChain) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type IHaveSignatureChainTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	SignatureHash []byte                 `protobuf:"bytes,2,opt,name=signature_hash,json=signatureHash,proto3" json:"signature_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IHaveSignatureChainTransaction) Reset() {
	*x = IHaveSignatureChainTransaction{}
	mi := &file_nodemessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IHaveSignatureChainTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IHaveSignatureChainTransaction) ProtoMessage() {}

func (x *IHaveSignatureChainTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IHaveSignatureChainTransaction.ProtoReflect.Descriptor instead.
func (*IHaveSignatureChainTransaction) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{21}
}

func (x *IHaveSignatureChainTransaction) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *IHaveSignatureChainTransaction) GetSignatureHash() []byte {
	if x != nil {
		return x.SignatureHash
	}
	return nil
}

type RequestSignatureChainTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignatureHash []byte                 `protobuf:"bytes,1,opt,name=signature_hash,json=signatureHash,proto3" json:"signature_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSignatureChainTransaction) Reset() {
	*x = RequestSignatureChainTransaction{}
	mi := &file_nodemessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSignatureChainTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSignatureChainTransaction) ProtoMessage() {}

func (x *RequestSignatureChainTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSignatureChainTransaction.ProtoReflect.Descriptor instead.
func (*RequestSignatureChainTransaction) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{22}
}

func (x *RequestSignatureChainTransaction) GetSignatureHash() []byte {
	if x != nil {
		return x.SignatureHash
	}
	return nil
}

type RequestSignatureChainTransactionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSignatureChainTransactionReply) Reset() {
	*x = RequestSignatureChainTransactionReply{}
	mi := &file_nodemessage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSignatureChainTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSignatureChainTransactionReply) ProtoMessage() {}

func (x *RequestSignatureChainTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSignatureChainTransactionReply.ProtoReflect.Descriptor instead.
func (*RequestSignatureChainTransactionReply) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{23}
}

func (x *RequestSignatureChainTransactionReply) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type PinSignatureChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinSignatureChain) Reset() {
	*x = PinSignatureChain{}
	mi := &file_nodemessage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinSignatureChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinSignatureChain) ProtoMessage() {}

func (x *PinSignatureChain) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinSignatureChain.ProtoReflect.Descriptor instead.
func (*PinSignatureChain) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{24}
}

func (x *PinSignatureChain) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SignatureChainObjectionUnsigned struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Height         uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	SignatureHash  []byte                 `protobuf:"bytes,2,opt,name=signature_hash,json=signatureHash,proto3" json:"signature_hash,omitempty"`
	ReporterPubkey []byte                 `protobuf:"bytes,3,opt,name=reporter_pubkey,json=reporterPubkey,proto3" json:"reporter_pubkey,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignatureChainObjectionUnsigned) Reset() {
	*x = SignatureChainObjectionUnsigned{}
	mi := &file_nodemessage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureChainObjectionUnsigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureChainObjectionUnsigned) ProtoMessage() {}

func (x *SignatureChainObjectionUnsigned) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureChainObjectionUnsigned.ProtoReflect.Descriptor instead.
func (*SignatureChainObjectionUnsigned) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{25}
}

func (x *SignatureChainObjectionUnsigned) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SignatureChainObjectionUnsigned) GetSignatureHash() []byte {
	if x != nil {
		return x.SignatureHash
	}
	return nil
}

func (x *SignatureChainObjectionUnsigned) GetReporterPubkey() []byte {
	if x != nil {
		return x.ReporterPubkey
	}
	return nil
}

type SignatureChainObjectionSigned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureChainObjectionSigned) Reset() {
	*x = SignatureChainObjectionSigned{}
	mi := &file_nodemessage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureChainObjectionSigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureChainObjectionSigned) ProtoMessage() {}

func (x *SignatureChainObjectionSigned) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureChainObjectionSigned.ProtoReflect.Descriptor instead.
func (*SignatureChainObjectionSigned) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{26}
}

func (x *SignatureChainObjectionSigned) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignatureChainObjectionSigned) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// sync txn pool
type TxnPoolHashAndCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolHash      []byte                 `protobuf:"bytes,1,opt,name=pool_hash,json=poolHash,proto3" json:"pool_hash,omitempty"`
	TxnCount      uint32                 `protobuf:"varint,2,opt,name=txn_count,json=txnCount,proto3" json:"txn_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnPoolHashAndCount) Reset() {
	*x = TxnPoolHashAndCount{}
	mi := &file_nodemessage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnPoolHashAndCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnPoolHashAndCount) ProtoMessage() {}

func (x *TxnPoolHashAndCount) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnPoolHashAndCount.ProtoReflect.Descriptor instead.
func (*TxnPoolHashAndCount) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{27}
}

func (x *TxnPoolHashAndCount) GetPoolHash() []byte {
	if x != nil {
		return x.PoolHash
	}
	return nil
}

func (x *TxnPoolHashAndCount) GetTxnCount() uint32 {
	if x != nil {
		return x.TxnCount
	}
	return 0
}

type AddrNonce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrNonce) Reset() {
	*x = AddrNonce{}
	mi := &file_nodemessage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrNonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrNonce) ProtoMessage() {}

func (x *AddrNonce) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrNonce.ProtoReflect.Descriptor instead.
func (*AddrNonce) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{28}
}

func (x *AddrNonce) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AddrNonce) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type RequestSyncTxnPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      int64                  `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	AddrNonce     []*AddrNonce           `protobuf:"bytes,2,rep,name=addrNonce,proto3" json:"addrNonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSyncTxnPool) Reset() {
	*x = RequestSyncTxnPool{}
	mi := &file_nodemessage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSyncTxnPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSyncTxnPool) ProtoMessage() {}

func (x *RequestSyncTxnPool) ProtoReflect() protoreflect.Message {
	mi := &file_nodemessage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSyncTxnPool.ProtoReflect.Descriptor instead.
func (*RequestSyncTxnPool) Descriptor() ([]byte, []int) {
	return file_nodemessage_proto_rawDescGZIP(), []int{29}
}

func (x *RequestSyncTxnPool) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RequestSyncTxnPool) GetAddrNonce() []*AddrNonce {
	if x != nil {
		return x.AddrNonce
	}
	return nil
}

var File_nodemessage_proto protoreflect.FileDescriptor

const file_nodemessage_proto_rawDesc = "" +
	"\n" +
	"\x11nodemessage.proto\x12\x02pb\x1a\n" +
	"node.proto\x1a\x0esigchain.proto\x1a\vblock.proto\x1a\x11transaction.proto\"_\n" +
	"\x0fUnsignedMessage\x122\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x0f.pb.MessageTypeR\vmessageType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"G\n" +
	"\rSignedMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"=\n" +
	"\x04Vote\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\"K\n" +
	"\x12IHaveBlockProposal\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\"\xb5\x01\n" +
	"\x14RequestBlockProposal\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.pb.RequestTransactionTypeR\x04type\x12&\n" +
	"\x0fshort_hash_salt\x18\x03 \x01(\fR\rshortHashSalt\x12&\n" +
	"\x0fshort_hash_size\x18\x04 \x01(\rR\rshortHashSize\"i\n" +
	"\x19RequestBlockProposalReply\x12\x1f\n" +
	"\x05block\x18\x01 \x01(\v2\t.pb.BlockR\x05block\x12+\n" +
	"\x11transactions_hash\x18\x02 \x03(\fR\x10transactionsHash\"\xe9\x01\n" +
	"\x1bRequestProposalTransactions\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.pb.RequestTransactionTypeR\x04type\x12&\n" +
	"\x0fshort_hash_salt\x18\x03 \x01(\fR\rshortHashSalt\x12&\n" +
	"\x0fshort_hash_size\x18\x04 \x01(\rR\rshortHashSize\x12+\n" +
	"\x11transactions_hash\x18\x05 \x03(\fR\x10transactionsHash\"W\n" +
	" RequestProposalTransactionsReply\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactions\"\x13\n" +
	"\x11GetConsensusState\"\xf6\x01\n" +
	"\x16GetConsensusStateReply\x12*\n" +
	"\x11ledger_block_hash\x18\x02 \x01(\fR\x0fledgerBlockHash\x12#\n" +
	"\rledger_height\x18\x01 \x01(\rR\fledgerHeight\x12)\n" +
	"\x10consensus_height\x18\x03 \x01(\rR\x0fconsensusHeight\x122\n" +
	"\x15min_verifiable_height\x18\x05 \x01(\rR\x13minVerifiableHeight\x12,\n" +
	"\n" +
	"sync_state\x18\x04 \x01(\x0e2\r.pb.SyncStateR\tsyncState\"S\n" +
	"\x0fGetBlockHeaders\x12!\n" +
	"\fstart_height\x18\x01 \x01(\rR\vstartHeight\x12\x1d\n" +
	"\n" +
	"end_height\x18\x02 \x01(\rR\tendHeight\"G\n" +
	"\x14GetBlockHeadersReply\x12/\n" +
	"\rblock_headers\x18\x01 \x03(\v2\n" +
	".pb.HeaderR\fblockHeaders\"M\n" +
	"\tGetBlocks\x12!\n" +
	"\fstart_height\x18\x01 \x01(\rR\vstartHeight\x12\x1d\n" +
	"\n" +
	"end_height\x18\x02 \x01(\rR\tendHeight\"3\n" +
	"\x0eGetBlocksReply\x12!\n" +
	"\x06blocks\x18\x01 \x03(\v2\t.pb.BlockR\x06blocks\"\"\n" +
	"\fStateRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\x1f\n" +
	"\tStateNode\x12\x12\n" +
	"\x04node\x18\x01 \x01(\fR\x04node\"1\n" +
	"\tGetStates\x12$\n" +
	"\x04reqs\x18\x01 \x03(\v2\x10.pb.StateRequestR\x04reqs\"5\n" +
	"\x0eGetStatesReply\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.pb.StateNodeR\x05nodes\"\x90\x02\n" +
	"\x05Relay\x12%\n" +
	"\x0esrc_identifier\x18\x01 \x01(\tR\rsrcIdentifier\x12\x1d\n" +
	"\n" +
	"src_pubkey\x18\x06 \x01(\fR\tsrcPubkey\x12\x17\n" +
	"\adest_id\x18\x02 \x01(\fR\x06destId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12.\n" +
	"\x13max_holding_seconds\x18\x05 \x01(\rR\x11maxHoldingSeconds\x12\x1d\n" +
	"\n" +
	"block_hash\x18\a \x01(\fR\tblockHash\x12\x1b\n" +
	"\tlast_hash\x18\b \x01(\fR\blastHash\x12\"\n" +
	"\rsig_chain_len\x18\t \x01(\rR\vsigChainLen\"C\n" +
	"\fTransactions\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactions\"g\n" +
	"\x17BacktrackSignatureChain\x128\n" +
	"\x0fsig_chain_elems\x18\x01 \x03(\v2\x10.pb.SigChainElemR\rsigChainElems\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"_\n" +
	"\x1eIHaveSignatureChainTransaction\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\x12%\n" +
	"\x0esignature_hash\x18\x02 \x01(\fR\rsignatureHash\"I\n" +
	" RequestSignatureChainTransaction\x12%\n" +
	"\x0esignature_hash\x18\x01 \x01(\fR\rsignatureHash\"Z\n" +
	"%RequestSignatureChainTransactionReply\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\"'\n" +
	"\x11PinSignatureChain\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\x89\x01\n" +
	"\x1fSignatureChainObjectionUnsigned\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\x12%\n" +
	"\x0esignature_hash\x18\x02 \x01(\fR\rsignatureHash\x12'\n" +
	"\x0freporter_pubkey\x18\x03 \x01(\fR\x0ereporterPubkey\"W\n" +
	"\x1dSignatureChainObjectionSigned\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"O\n" +
	"\x13TxnPoolHashAndCount\x12\x1b\n" +
	"\tpool_hash\x18\x01 \x01(\fR\bpoolHash\x12\x1b\n" +
	"\ttxn_count\x18\x02 \x01(\rR\btxnCount\";\n" +
	"\tAddrNonce\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\"]\n" +
	"\x12RequestSyncTxnPool\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x03R\bduration\x12+\n" +
	"\taddrNonce\x18\x02 \x03(\v2\r.pb.AddrNonceR\taddrNonce*\xc3\x06\n" +
	"\vMessageType\x12'\n" +
	"#MESSAGE_TYPE_PLACEHOLDER_DO_NOT_USE\x10\x00\x12\b\n" +
	"\x04VOTE\x10\x01\x12\x19\n" +
	"\x15I_HAVE_BLOCK_PROPOSAL\x10\x02\x12\x1a\n" +
	"\x16REQUEST_BLOCK_PROPOSAL\x10\x03\x12 \n" +
	"\x1cREQUEST_BLOCK_PROPOSAL_REPLY\x10\x04\x12\x17\n" +
	"\x13GET_CONSENSUS_STATE\x10\x05\x12\x1d\n" +
	"\x19GET_CONSENSUS_STATE_REPLY\x10\x06\x12\x15\n" +
	"\x11GET_BLOCK_HEADERS\x10\a\x12\x1b\n" +
	"\x17GET_BLOCK_HEADERS_REPLY\x10\b\x12\x0e\n" +
	"\n" +
	"GET_BLOCKS\x10\t\x12\x14\n" +
	"\x10GET_BLOCKS_REPLY\x10\n" +
	"\x12\t\n" +
	"\x05RELAY\x10\v\x12\x10\n" +
	"\fTRANSACTIONS\x10\f\x12\x1d\n" +
	"\x19BACKTRACK_SIGNATURE_CHAIN\x10\r\x12!\n" +
	"\x1dREQUEST_PROPOSAL_TRANSACTIONS\x10\x0e\x12'\n" +
	"#REQUEST_PROPOSAL_TRANSACTIONS_REPLY\x10\x0f\x12&\n" +
	"\"I_HAVE_SIGNATURE_CHAIN_TRANSACTION\x10\x10\x12'\n" +
	"#REQUEST_SIGNATURE_CHAIN_TRANSACTION\x10\x11\x12-\n" +
	")REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY\x10\x12\x12\x17\n" +
	"\x13PIN_SIGNATURE_CHAIN\x10\x13\x12\x1d\n" +
	"\x19SIGNATURE_CHAIN_OBJECTION\x10\x14\x12\x0e\n" +
	"\n" +
	"GET_STATES\x10\x15\x12\x14\n" +
	"\x10GET_STATES_REPLY\x10\x16\x12\x15\n" +
	"\x11REQ_TXN_POOL_HASH\x10\x17\x12\x15\n" +
	"\x11RPL_TXN_POOL_HASH\x10\x18\x12\x15\n" +
	"\x11REQ_SYNC_TXN_POOL\x10\x19\x12\x15\n" +
	"\x11RPL_SYNC_TXN_POOL\x10\x1a\x12\x12\n" +
	"\x0eREQ_ADDR_NONCE\x10\x1b\x12\x12\n" +
	"\x0eRPL_ADDR_NONCE\x10\x1c\x12\x15\n" +
	"\x11REQ_SYNC_ADDR_TXN\x10\x1d\x12\x15\n" +
	"\x11RPL_SYNC_ADDR_TXN\x10\x1e*C\n" +
	"\x18AllowedSignedMessageType\x12'\n" +
	"#ALLOW_SIGNED_PLACEHOLDER_DO_NOT_USE\x10\x00*\x8d\n" +
	"\n" +
	"\x1aAllowedUnsignedMessageType\x12)\n" +
	"%ALLOW_UNSIGNED_PLACEHOLDER_DO_NOT_USE\x10\x00\x12\x17\n" +
	"\x13ALLOW_UNSIGNED_VOTE\x10\x01\x12(\n" +
	"$ALLOW_UNSIGNED_I_HAVE_BLOCK_PROPOSAL\x10\x02\x12)\n" +
	"%ALLOW_UNSIGNED_REQUEST_BLOCK_PROPOSAL\x10\x03\x12&\n" +
	"\"ALLOW_UNSIGNED_REQUEST_BLOCK_REPLY\x10\x04\x12&\n" +
	"\"ALLOW_UNSIGNED_GET_CONSENSUS_STATE\x10\x05\x12,\n" +
	"(ALLOW_UNSIGNED_GET_CONSENSUS_STATE_REPLY\x10\x06\x12$\n" +
	" ALLOW_UNSIGNED_GET_BLOCK_HEADERS\x10\a\x12*\n" +
	"&ALLOW_UNSIGNED_GET_BLOCK_HEADERS_REPLY\x10\b\x12\x1d\n" +
	"\x19ALLOW_UNSIGNED_GET_BLOCKS\x10\t\x12#\n" +
	"\x1fALLOW_UNSIGNED_GET_BLOCKS_REPLY\x10\n" +
	"\x12\x18\n" +
	"\x14ALLOW_UNSIGNED_RELAY\x10\v\x12\x1f\n" +
	"\x1bALLOW_UNSIGNED_TRANSACTIONS\x10\f\x12,\n" +
	"(ALLOW_UNSIGNED_BACKTRACK_SIGNATURE_CHAIN\x10\r\x120\n" +
	",ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS\x10\x0e\x126\n" +
	"2ALLOW_UNSIGNED_REQUEST_PROPOSAL_TRANSACTIONS_REPLY\x10\x0f\x125\n" +
	"1ALLOW_UNSIGNED_I_HAVE_SIGNATURE_CHAIN_TRANSACTION\x10\x10\x126\n" +
	"2ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION\x10\x11\x12<\n" +
	"8ALLOW_UNSIGNED_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY\x10\x12\x12&\n" +
	"\"ALLOW_UNSIGNED_PIN_SIGNATURE_CHAIN\x10\x13\x12,\n" +
	"(ALLOW_UNSIGNED_SIGNATURE_CHAIN_OBJECTION\x10\x14\x12\x1d\n" +
	"\x19ALLOW_UNSIGNED_GET_STATES\x10\x15\x12#\n" +
	"\x1fALLOW_UNSIGNED_GET_STATES_REPLY\x10\x16\x12$\n" +
	" ALLOW_UNSIGNED_REQ_TXN_POOL_HASH\x10\x17\x12$\n" +
	" ALLOW_UNSIGNED_RPL_TXN_POOL_HASH\x10\x18\x12$\n" +
	" ALLOW_UNSIGNED_REQ_SYNC_TXN_POOL\x10\x19\x12$\n" +
	" ALLOW_UNSIGNED_RPL_SYNC_TXN_POOL\x10\x1a\x12!\n" +
	"\x1dALLOW_UNSIGNED_REQ_ADDR_NONCE\x10\x1b\x12!\n" +
	"\x1dALLOW_UNSIGNED_RPL_ADDR_NONCE\x10\x1c\x12$\n" +
	" ALLOW_UNSIGNED_REQ_SYNC_ADDR_TXN\x10\x1d\x12$\n" +
	" ALLOW_UNSIGNED_RPL_SYNC_ADDR_TXN\x10\x1e*\x96\t\n" +
	"\x18AllowedDirectMessageType\x12'\n" +
	"#ALLOW_DIRECT_PLACEHOLDER_DO_NOT_USE\x10\x00\x12\x15\n" +
	"\x11ALLOW_DIRECT_VOTE\x10\x01\x12&\n" +
	"\"ALLOW_DIRECT_I_HAVE_BLOCK_PROPOSAL\x10\x02\x12'\n" +
	"#ALLOW_DIRECT_REQUEST_BLOCK_PROPOSAL\x10\x03\x12$\n" +
	" ALLOW_DIRECT_REQUEST_BLOCK_REPLY\x10\x04\x12$\n" +
	" ALLOW_DIRECT_GET_CONSENSUS_STATE\x10\x05\x12*\n" +
	"&ALLOW_DIRECT_GET_CONSENSUS_STATE_REPLY\x10\x06\x12\"\n" +
	"\x1eALLOW_DIRECT_GET_BLOCK_HEADERS\x10\a\x12(\n" +
	"$ALLOW_DIRECT_GET_BLOCK_HEADERS_REPLY\x10\b\x12\x1b\n" +
	"\x17ALLOW_DIRECT_GET_BLOCKS\x10\t\x12!\n" +
	"\x1dALLOW_DIRECT_GET_BLOCKS_REPLY\x10\n" +
	"\x12*\n" +
	"&ALLOW_DIRECT_BACKTRACK_SIGNATURE_CHAIN\x10\r\x12.\n" +
	"*ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS\x10\x0e\x124\n" +
	"0ALLOW_DIRECT_REQUEST_PROPOSAL_TRANSACTIONS_REPLY\x10\x0f\x123\n" +
	"/ALLOW_DIRECT_I_HAVE_SIGNATURE_CHAIN_TRANSACTION\x10\x10\x124\n" +
	"0ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION\x10\x11\x12:\n" +
	"6ALLOW_DIRECT_REQUEST_SIGNATURE_CHAIN_TRANSACTION_REPLY\x10\x12\x12$\n" +
	" ALLOW_DIRECT_PIN_SIGNATURE_CHAIN\x10\x13\x12*\n" +
	"&ALLOW_DIRECT_SIGNATURE_CHAIN_OBJECTION\x10\x14\x12\x1b\n" +
	"\x17ALLOW_DIRECT_GET_STATES\x10\x15\x12!\n" +
	"\x1dALLOW_DIRECT_GET_STATES_REPLY\x10\x16\x12\"\n" +
	"\x1eALLOW_DIRECT_REQ_TXN_POOL_HASH\x10\x17\x12\"\n" +
	"\x1eALLOW_DIRECT_RPL_TXN_POOL_HASH\x10\x18\x12\"\n" +
	"\x1eALLOW_DIRECT_REQ_SYNC_TXN_POOL\x10\x19\x12\"\n" +
	"\x1eALLOW_DIRECT_RPL_SYNC_TXN_POOL\x10\x1a\x12\x1f\n" +
	"\x1bALLOW_DIRECT_REQ_ADDR_NONCE\x10\x1b\x12\x1f\n" +
	"\x1bALLOW_DIRECT_RPL_ADDR_NONCE\x10\x1c\x12\"\n" +
	"\x1eALLOW_DIRECT_REQ_SYNC_ADDR_TXN\x10\x1d\x12\"\n" +
	"\x1eALLOW_DIRECT_RPL_SYNC_ADDR_TXN\x10\x1e*X\n" +
	"\x17AllowedRelayMessageType\x12&\n" +
	"\"ALLOW_RELAY_PLACEHOLDER_DO_NOT_USE\x10\x00\x12\x15\n" +
	"\x11ALLOW_RELAY_RELAY\x10\v*y\n" +
	"\x1fAllowedBroadcastPushMessageType\x12/\n" +
	"+ALLOW_BROADCAST_PUSH_PLACEHOLDER_DO_NOT_USE\x10\x00\x12%\n" +
	"!ALLOW_BROADCAST_PUSH_TRANSACTIONS\x10\f*R\n" +
	"\x1fAllowedBroadcastPullMessageType\x12/\n" +
	"+ALLOW_BROADCAST_PULL_PLACEHOLDER_DO_NOT_USE\x10\x00*y\n" +
	"\x1fAllowedBroadcastTreeMessageType\x12/\n" +
	"+ALLOW_BROADCAST_TREE_PLACEHOLDER_DO_NOT_USE\x10\x00\x12%\n" +
	"!ALLOW_BROADCAST_TREE_TRANSACTIONS\x10\f*x\n" +
	"\x16RequestTransactionType\x12\x1c\n" +
	"\x18REQUEST_FULL_TRANSACTION\x10\x00\x12\x1c\n" +
	"\x18REQUEST_TRANSACTION_HASH\x10\x01\x12\"\n" +
	"\x1eREQUEST_TRANSACTION_SHORT_HASH\x10\x02B\x06Z\x04./pbb\x06proto3"

var (
	file_nodemessage_proto_rawDescOnce sync.Once
	file_nodemessage_proto_rawDescData []byte
)

func file_nodemessage_proto_rawDescGZIP() []byte {
	file_nodemessage_proto_rawDescOnce.Do(func() {
		file_nodemessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodemessage_proto_rawDesc), len(file_nodemessage_proto_rawDesc)))
	})
	return file_nodemessage_proto_rawDescData
}

var file_nodemessage_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_nodemessage_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_nodemessage_proto_goTypes = []any{
	(MessageType)(0),                              // 0: pb.MessageType
	(AllowedSignedMessageType)(0),                 // 1: pb.AllowedSignedMessageType
	(AllowedUnsignedMessageType)(0),               // 2: pb.AllowedUnsignedMessageType
	(AllowedDirectMessageType)(0),                 // 3: pb.AllowedDirectMessageType
	(AllowedRelayMessageType)(0),                  // 4: pb.AllowedRelayMessageType
	(AllowedBroadcastPushMessageType)(0),          // 5: pb.AllowedBroadcastPushMessageType
	(AllowedBroadcastPullMessageType)(0),          // 6: pb.AllowedBroadcastPullMessageType
	(AllowedBroadcastTreeMessageType)(0),          // 7: pb.AllowedBroadcastTreeMessageType
	(RequestTransactionType)(0),                   // 8: pb.RequestTransactionType
	(*UnsignedMessage)(nil),                       // 9: pb.UnsignedMessage
	(*SignedMessage)(nil),                         // 10: pb.SignedMessage
	(*Vote)(nil),                                  // 11: pb.Vote
	(*IHaveBlockProposal)(nil),                    // 12: pb.IHaveBlockProposal
	(*RequestBlockProposal)(nil),                  // 13: pb.RequestBlockProposal
	(*RequestBlockProposalReply)(nil),             // 14: pb.RequestBlockProposalReply
	(*RequestProposalTransactions)(nil),           // 15: pb.RequestProposalTransactions
	(*RequestProposalTransactionsReply)(nil),      // 16: pb.RequestProposalTransactionsReply
	(*GetConsensusState)(nil),                     // 17: pb.GetConsensusState
	(*GetConsensusStateReply)(nil),                // 18: pb.GetConsensusStateReply
	(*GetBlockHeaders)(nil),                       // 19: pb.GetBlockHeaders
	(*GetBlockHeadersReply)(nil),                  // 20: pb.GetBlockHeadersReply
	(*GetBlocks)(nil),                             // 21: pb.GetBlocks
	(*GetBlocksReply)(nil),                        // 22: pb.GetBlocksReply
	(*StateRequest)(nil),                          // 23: pb.StateRequest
	(*StateNode)(nil),                             // 24: pb.StateNode
	(*GetStates)(nil),                             // 25: pb.GetStates
	(*GetStatesReply)(nil),                        // 26: pb.GetStatesReply
	(*Relay)(nil),                                 // 27: pb.Relay
	(*Transactions)(nil),                          // 28: pb.Transactions
	(*BacktrackSignatureChain)(nil),               // 29: pb.BacktrackSignatureChain
	(*IHaveSignatureChainTransaction)(nil),        // 30: pb.IHaveSignatureChainTransaction
	(*RequestSignatureChainTransaction)(nil),      // 31: pb.RequestSignatureChainTransaction
	(*RequestSignatureChainTransactionReply)(nil), // 32: pb.RequestSignatureChainTransactionReply
	(*PinSignatureChain)(nil),                     // 33: pb.PinSignatureChain
	(*SignatureChainObjectionUnsigned)(nil),       // 34: pb.SignatureChainObjectionUnsigned
	(*SignatureChainObjectionSigned)(nil),         // 35: pb.SignatureChainObjectionSigned
	(*TxnPoolHashAndCount)(nil),                   // 36: pb.TxnPoolHashAndCount
	(*AddrNonce)(nil),                             // 37: pb.AddrNonce
	(*RequestSyncTxnPool)(nil),                    // 38: pb.RequestSyncTxnPool
	(*Block)(nil),                                 // 39: pb.Block
	(*Transaction)(nil),                           // 40: pb.Transaction
	(SyncState)(0),                                // 41: pb.SyncState
	(*Header)(nil),                                // 42: pb.Header
	(*SigChainElem)(nil),                          // 43: pb.SigChainElem
}
var file_nodemessage_proto_depIdxs = []int32{
	0,  // 0: pb.UnsignedMessage.message_type:type_name -> pb.MessageType
	8,  // 1: pb.RequestBlockProposal.type:type_name -> pb.RequestTransactionType
	39, // 2: pb.RequestBlockProposalReply.block:type_name -> pb.Block
	8,  // 3: pb.RequestProposalTransactions.type:type_name -> pb.RequestTransactionType
	40, // 4: pb.RequestProposalTransactionsReply.transactions:type_name -> pb.Transaction
	41, // 5: pb.GetConsensusStateReply.sync_state:type_name -> pb.SyncState
	42, // 6: pb.GetBlockHeadersReply.block_headers:type_name -> pb.Header
	39, // 7: pb.GetBlocksReply.blocks:type_name -> pb.Block
	23, // 8: pb.GetStates.reqs:type_name -> pb.StateRequest
	24, // 9: pb.GetStatesReply.nodes:type_name -> pb.StateNode
	40, // 10: pb.Transactions.transactions:type_name -> pb.Transaction
	43, // 11: pb.BacktrackSignatureChain.sig_chain_elems:type_name -> pb.SigChainElem
	40, // 12: pb.RequestSignatureChainTransactionReply.transaction:type_name -> pb.Transaction
	37, // 13: pb.RequestSyncTxnPool.addrNonce:type_name -> pb.AddrNonce
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_nodemessage_proto_init() }
func file_nodemessage_proto_init() {
	if File_nodemessage_proto != nil {
		return
	}
	file_node_proto_init()
	file_sigchain_proto_init()
	file_block_proto_init()
	file_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodemessage_proto_rawDesc), len(file_nodemessage_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodemessage_proto_goTypes,
		DependencyIndexes: file_nodemessage_proto_depIdxs,
		EnumInfos:         file_nodemessage_proto_enumTypes,
		MessageInfos:      file_nodemessage_proto_msgTypes,
	}.Build()
	File_nodemessage_proto = out.File
	file_nodemessage_proto_goTypes = nil
	file_nodemessage_proto_depIdxs = nil
}
