// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: pb/sigchain.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SigAlgo int32

const (
	SigAlgo_SIGNATURE SigAlgo = 0
	SigAlgo_HASH      SigAlgo = 1
)

// Enum value maps for SigAlgo.
var (
	SigAlgo_name = map[int32]string{
		0: "SIGNATURE",
		1: "HASH",
	}
	SigAlgo_value = map[string]int32{
		"SIGNATURE": 0,
		"HASH":      1,
	}
)

func (x SigAlgo) Enum() *SigAlgo {
	p := new(SigAlgo)
	*p = x
	return p
}

func (x SigAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SigAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_sigchain_proto_enumTypes[0].Descriptor()
}

func (SigAlgo) Type() protoreflect.EnumType {
	return &file_pb_sigchain_proto_enumTypes[0]
}

func (x SigAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SigAlgo.Descriptor instead.
func (SigAlgo) EnumDescriptor() ([]byte, []int) {
	return file_pb_sigchain_proto_rawDescGZIP(), []int{0}
}

type SigChainElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         []byte  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NextPubkey []byte  `protobuf:"bytes,2,opt,name=next_pubkey,json=nextPubkey,proto3" json:"next_pubkey,omitempty"`
	Mining     bool    `protobuf:"varint,3,opt,name=mining,proto3" json:"mining,omitempty"`
	Signature  []byte  `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SigAlgo    SigAlgo `protobuf:"varint,5,opt,name=sig_algo,json=sigAlgo,proto3,enum=pb.SigAlgo" json:"sig_algo,omitempty"`
	Vrf        []byte  `protobuf:"bytes,6,opt,name=vrf,proto3" json:"vrf,omitempty"`
	Proof      []byte  `protobuf:"bytes,7,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *SigChainElem) Reset() {
	*x = SigChainElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sigchain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigChainElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigChainElem) ProtoMessage() {}

func (x *SigChainElem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sigchain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigChainElem.ProtoReflect.Descriptor instead.
func (*SigChainElem) Descriptor() ([]byte, []int) {
	return file_pb_sigchain_proto_rawDescGZIP(), []int{0}
}

func (x *SigChainElem) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SigChainElem) GetNextPubkey() []byte {
	if x != nil {
		return x.NextPubkey
	}
	return nil
}

func (x *SigChainElem) GetMining() bool {
	if x != nil {
		return x.Mining
	}
	return false
}

func (x *SigChainElem) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigChainElem) GetSigAlgo() SigAlgo {
	if x != nil {
		return x.SigAlgo
	}
	return SigAlgo_SIGNATURE
}

func (x *SigChainElem) GetVrf() []byte {
	if x != nil {
		return x.Vrf
	}
	return nil
}

func (x *SigChainElem) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type SigChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce      uint32          `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	DataSize   uint32          `protobuf:"varint,2,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	BlockHash  []byte          `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	SrcId      []byte          `protobuf:"bytes,4,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	SrcPubkey  []byte          `protobuf:"bytes,5,opt,name=src_pubkey,json=srcPubkey,proto3" json:"src_pubkey,omitempty"`
	DestId     []byte          `protobuf:"bytes,6,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	DestPubkey []byte          `protobuf:"bytes,7,opt,name=dest_pubkey,json=destPubkey,proto3" json:"dest_pubkey,omitempty"`
	Elems      []*SigChainElem `protobuf:"bytes,8,rep,name=elems,proto3" json:"elems,omitempty"`
}

func (x *SigChain) Reset() {
	*x = SigChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sigchain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigChain) ProtoMessage() {}

func (x *SigChain) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sigchain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigChain.ProtoReflect.Descriptor instead.
func (*SigChain) Descriptor() ([]byte, []int) {
	return file_pb_sigchain_proto_rawDescGZIP(), []int{1}
}

func (x *SigChain) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SigChain) GetDataSize() uint32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *SigChain) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SigChain) GetSrcId() []byte {
	if x != nil {
		return x.SrcId
	}
	return nil
}

func (x *SigChain) GetSrcPubkey() []byte {
	if x != nil {
		return x.SrcPubkey
	}
	return nil
}

func (x *SigChain) GetDestId() []byte {
	if x != nil {
		return x.DestId
	}
	return nil
}

func (x *SigChain) GetDestPubkey() []byte {
	if x != nil {
		return x.DestPubkey
	}
	return nil
}

func (x *SigChain) GetElems() []*SigChainElem {
	if x != nil {
		return x.Elems
	}
	return nil
}

var File_pb_sigchain_proto protoreflect.FileDescriptor

var file_pb_sigchain_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x73, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xc5, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74,
	0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6e,
	0x65, 0x78, 0x74, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x26, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x67, 0x41, 0x6c, 0x67, 0x6f, 0x52, 0x07,
	0x73, 0x69, 0x67, 0x41, 0x6c, 0x67, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x72, 0x66, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x72, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22,
	0xf4, 0x01, 0x0a, 0x08, 0x53, 0x69, 0x67, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x72, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x73, 0x72, 0x63, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x72, 0x63, 0x5f, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x72, 0x63, 0x50, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x26,
	0x0a, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x69, 0x67, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x52,
	0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x2a, 0x22, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x41, 0x6c, 0x67,
	0x6f, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x49, 0x47, 0x4e, 0x41, 0x54, 0x55, 0x52, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x41, 0x53, 0x48, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_sigchain_proto_rawDescOnce sync.Once
	file_pb_sigchain_proto_rawDescData = file_pb_sigchain_proto_rawDesc
)

func file_pb_sigchain_proto_rawDescGZIP() []byte {
	file_pb_sigchain_proto_rawDescOnce.Do(func() {
		file_pb_sigchain_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_sigchain_proto_rawDescData)
	})
	return file_pb_sigchain_proto_rawDescData
}

var file_pb_sigchain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_sigchain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_sigchain_proto_goTypes = []interface{}{
	(SigAlgo)(0),         // 0: pb.SigAlgo
	(*SigChainElem)(nil), // 1: pb.SigChainElem
	(*SigChain)(nil),     // 2: pb.SigChain
}
var file_pb_sigchain_proto_depIdxs = []int32{
	0, // 0: pb.SigChainElem.sig_algo:type_name -> pb.SigAlgo
	1, // 1: pb.SigChain.elems:type_name -> pb.SigChainElem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_sigchain_proto_init() }
func file_pb_sigchain_proto_init() {
	if File_pb_sigchain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_sigchain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigChainElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sigchain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_sigchain_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_sigchain_proto_goTypes,
		DependencyIndexes: file_pb_sigchain_proto_depIdxs,
		EnumInfos:         file_pb_sigchain_proto_enumTypes,
		MessageInfos:      file_pb_sigchain_proto_msgTypes,
	}.Build()
	File_pb_sigchain_proto = out.File
	file_pb_sigchain_proto_rawDesc = nil
	file_pb_sigchain_proto_goTypes = nil
	file_pb_sigchain_proto_depIdxs = nil
}
